name: Python CI

on:
  push:
    branches:
      - alltalkbeta
  pull_request:
    branches:
      - alltalkbeta

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f system/requirements/requirements_unit_test.txt ]; then
            pip install -r system/requirements/requirements_unit_test.txt;
          fi

      - name: Test with pytest
        run: |
          pytest test --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

      - name: Surface failing tests
        if: always()
        uses: pmeier/pytest-results-action@v0.6.0
        with:
          path: junit/test-results.xml
          summary: true
          display-options: fEX
          fail-on-empty: false
          title: Test results
